### PR TITLE
DMN model for vacationDays

### PR DESCRIPTION
**Pull request by tarilabs**
image
image

wdyt @mswiderski ?
/cc @evacchi @mariofusco @etirelli

### CODE REVIEW

**Comment by mswiderski** [comment]
looks (and works) good, can we have similar for tax rate and payment date?

**Comment by tarilabs** [comment]
on it

**Comment by tarilabs** [comment]
image
image

**Comment by tarilabs** [comment]
image
image

**Comment by tarilabs** [comment]
> can we have similar for tax rate and payment date?

done with separate commits so you can incorporate as a whole or as-needed by cherry-pick.

**Review by evacchi — APPROVED** [review]
Nice :+1: I'd say good job!

**Comment by tarilabs** [comment]
update of 6fce5f0
image

**Comment by mswiderski** [comment]
all merged manually, thanks @tarilabs

**Pull request closed without merging**
